<?php $corpus = array (
  'corneillep_veuve34' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'La Veuve',
    'date' => 1632,
    'lustrum' => '1631-1635',
    'genre' => 'Comédie',
    'play' => 'corneillep_veuve34',
    'titleId' => 'LaVeuve',
    'genreId' => 'Comedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'PHILISTE' => 'PHILISTE',
      'ALCIDON' => 'ALCIDON',
      'NOURRICE' => 'LA NOURRICE de Clarice',
      'CHRYSANTE' => 'CHRYSANTE',
      'DORIS' => 'DORIS',
      'GERON' => 'GÉRON',
      'CLARICE' => 'CLARICE',
      'CELIDAN' => 'CÉLIDAN',
      'LYCAS' => 'LYCAS',
      'POLYMAS' => 'POLYMAS',
      'DORASTE' => 'DORASTE',
      'LISTOR' => 'LISTOR',
    ),
  ),
  'corneillep_toison' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'La Conquête de la Toison d\'or',
    'date' => 1660,
    'lustrum' => '1656-1660',
    'genre' => 'Tragédie',
    'play' => 'corneillep_toison',
    'titleId' => 'LaConquetedelaToisondor',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'MEDEE' => 'MÉDÉE',
      'CHALCIOPE' => 'CHALCIOPE',
      'PAIX' => '',
      'FRANCE' => '',
      'VICTOIRE' => '',
      'HYMENEE' => '',
      'DISCORDE' => '',
      'ENVIE' => '',
      'AMOUR' => '',
      'VOIX' => '',
      'SIRENES' => '',
      'PALLAS' => '',
      'CHOEUR' => '',
      'AAETE' => 'AAETE',
      'ABSYRTE' => 'ABSYRTE',
      'JASON' => 'JASON',
      'PELEE' => 'PÉLÉE',
      'IPHITE' => 'IPHITE',
      'ORPHEE' => 'ORPHÉE',
      'IRIS' => 'IRIS',
      'JUNON' => 'JUNON',
      'HYPSIPYLE' => 'HYPSIPYLE',
      'GLAUQUE' => 'GLAUQUE',
      'ZETHES' => 'ZÉTHÈS',
      'CALAIS' => 'CALAIS',
      'SOLEIL' => 'SOLEIL',
      'JUPITER' => 'JUPITER',
    ),
  ),
  'corneillep_tite' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Tite et Bérénice',
    'date' => 1670,
    'lustrum' => '1666-1670',
    'genre' => 'Comédie héroïque',
    'play' => 'corneillep_tite',
    'titleId' => 'TiteetBerenice',
    'genreId' => 'Comedieheroique',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'DOMITIE' => 'DOMITIE',
      'PLAUTINE' => 'PLAUTINE',
      'DOMITIAN' => 'DOMITIAN',
      'ALBIN' => 'ALBIN',
      'TITE' => 'TITE',
      'FLAVIAN' => 'FLAVIAN',
      'BERENICE' => 'BÉRÉNICE',
      'PHILON' => 'PHILON',
    ),
  ),
  'corneillep_theodore' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Théodore',
    'date' => 1645,
    'lustrum' => '1641-1645',
    'genre' => 'Tragédie',
    'play' => 'corneillep_theodore',
    'titleId' => 'Theodore',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'PLACIDE' => 'PLACIDE',
      'CLEOBULE' => 'CLÉOBULE',
      'MARCELLE' => 'MARCELLE',
      'STEPHANIE' => 'STÉPHANIE',
      'VALENS' => 'VALENS',
      'THEODORE' => 'THÉODORE',
      'PAULIN' => 'PAULIN',
      'LYCANTE' => 'LYCANTE',
      'DIDYME' => 'DIDYME',
    ),
  ),
  'corneillep_surena' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Suréna',
    'date' => 1674,
    'lustrum' => '1671-1675',
    'genre' => 'Tragédie',
    'play' => 'corneillep_surena',
    'titleId' => 'Surena',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'EURYDICE' => 'EURYDICE',
      'ORMENE' => 'ORMÈNE',
      'PALMIS' => 'PALMIS',
      'SURENA' => 'SURÉNA',
      'PACORUS' => 'PACORUS',
      'SILLACE' => 'SILLACE',
      'ORODE' => 'ORODE',
    ),
  ),
  'corneillep_suivante' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'La Suivante',
    'date' => 1634,
    'lustrum' => '1631-1635',
    'genre' => 'Comédie',
    'play' => 'corneillep_suivante',
    'titleId' => 'LaSuivante',
    'genreId' => 'Comedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'DAMON' => 'DAMON',
      'THEANTE' => 'THÉANTE',
      'FLORAME' => 'FLORAME',
      'AMARANTE' => 'AMARANTE',
      'DAPHNIS' => 'DAPHNIS',
      'CELIE' => 'CÉLIE',
      'GERASTE' => 'GÉRASTE',
      'CLARIMOND' => 'CLARIMOND',
      'CLEON' => 'CLÉON',
      'POLEMON' => 'POLÉMON',
    ),
  ),
  'corneillep_suitementeur' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'La Suite du Menteur',
    'date' => 1644,
    'lustrum' => '1641-1645',
    'genre' => 'Comédie',
    'play' => 'corneillep_suitementeur',
    'titleId' => 'LaSuiteduMenteur',
    'genreId' => 'Comedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'CLITON' => 'CLITON',
      'DORANTE' => 'DORANTE',
      'LYSE' => 'LYSE',
      'CLEANDRE' => 'CLÉANDRE',
      'PREVOT' => 'UN PRÉVÔT',
      'MELISSE' => 'MÉLISSE',
      'PHILISTE' => 'PHILISTE',
    ),
  ),
  'corneillep_sophonisbe' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Sophonisbe',
    'date' => 1663,
    'lustrum' => '1661-1665',
    'genre' => 'Tragédie',
    'play' => 'corneillep_sophonisbe',
    'titleId' => 'Sophonisbe',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'BOCCHAR' => 'BOCCHAR',
      'SOPHONISBE' => 'SOPHONISBE',
      'HERMINIE' => 'HERMINIE',
      'ERYXE' => 'ÉRYXE',
      'BARCEE' => 'BARCÉE',
      'SYPHAX' => 'SYPHAX',
      'MASSINISSE' => 'MASSINISSE',
      'MEZETULLE' => 'MÉZÉTULLE',
      'LEPIDE' => 'LÉPIDE',
      'GARDES' => 'Gardes',
      'LELIUS' => 'LÉLIUS',
      'ALBIN' => 'ALBIN',
      'PAGE' => 'Page de Sophonisbe',
    ),
  ),
  'corneillep_sertorius' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Sertorius',
    'date' => 1662,
    'lustrum' => '1661-1665',
    'genre' => 'Tragédie',
    'play' => 'corneillep_sertorius',
    'titleId' => 'Sertorius',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'PERPENNA' => 'PERPENNA',
      'AUFIDE' => 'AUFIDE',
      'SERTORIUS' => 'SERTORIUS',
      'ARISTIE' => 'ARISTIE',
      'VIRIATE' => 'VIRIATE',
      'THAMIRE' => 'THAMIRE',
      'POMPEE' => 'POMPÉE',
      'ARCAS' => 'ARCAS',
      'CELSUS' => 'CELSUS',
    ),
  ),
  'corneillep_rodogune' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Rodogune',
    'date' => 1644,
    'lustrum' => '1641-1645',
    'genre' => 'Tragédie',
    'play' => 'corneillep_rodogune',
    'titleId' => 'Rodogune',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'LAONICE' => 'LAONICE',
      'TIMAGENE' => 'TIMAGÈNE',
      'ANTIOCHUS' => 'ANTIOCHUS',
      'SELEUCUS' => 'SÉLEUCUS',
      'RODOGUNE' => 'RODOGUNE',
      'CLEOPATRE' => 'CLÉOPÂTRE',
      'ORONTE' => 'ORONTE',
    ),
  ),
  'corneillep_pulcherie' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Pulchérie',
    'date' => 1672,
    'lustrum' => '1671-1675',
    'genre' => 'Comédie héroïque',
    'play' => 'corneillep_pulcherie',
    'titleId' => 'Pulcherie',
    'genreId' => 'Comedieheroique',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'PULCHERIE' => 'PULCHÉRIE',
      'LEON' => 'LÉON',
      'IRENE' => 'IRÈNE',
      'ASPAR' => 'ASPAR',
      'JUSTINE' => 'JUSTINE',
      'MARTIAN' => 'MARTIAN',
    ),
  ),
  'corneillep_polyeucte' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Polyeucte',
    'date' => 1643,
    'lustrum' => '1641-1645',
    'genre' => 'Tragédie',
    'play' => 'corneillep_polyeucte',
    'titleId' => 'Polyeucte',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'NEARQUE' => 'NÉARQUE',
      'POLYEUCTE' => 'POLYEUCTE',
      'PAULINE' => 'PAULINE',
      'STRATONICE' => 'STRATONICE',
      'FELIX' => 'FÉLIX',
      'ALBIN' => 'ALBIN',
      'SEVERE' => 'SÉVÈRE',
      'FABIAN' => 'FABIAN',
      'CLEON' => 'CLÉON',
    ),
  ),
  'corneillep_placeroyale' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'La Place Royale',
    'date' => 1634,
    'lustrum' => '1631-1635',
    'genre' => 'Comédie',
    'play' => 'corneillep_placeroyale',
    'titleId' => 'LaPlaceRoyale',
    'genreId' => 'Comedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'ANGELIQUE' => 'ANGÉLIQUE',
      'PHILIS' => 'PHILIS',
      'DORASTE' => 'DORASTE',
      'CLEANDRE' => 'CLÉANDRE',
      'ALIDOR' => 'ALIDOR',
      'POLYMAS' => 'POLYMAS',
      'LYSIS' => 'LYSIS',
      'LYCANTE' => 'LYCANTE',
    ),
  ),
  'corneillep_pertharite' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Pertharite',
    'date' => 1651,
    'lustrum' => '1651-1655',
    'genre' => 'Tragédie',
    'play' => 'corneillep_pertharite',
    'titleId' => 'Pertharite',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'RODELINDE' => 'RODELINDE',
      'UNULPHE' => 'UNULPHE',
      'EDWIGE' => 'ÉDVIGE',
      'GRIMOALD' => 'GRIMOALD',
      'GARIBALDE' => 'GARIBALDE',
      'PERTHARITE' => 'PERTHARITE',
      'SOLDAT' => 'Soldats',
    ),
  ),
  'corneillep_othon' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Othon',
    'date' => 1664,
    'lustrum' => '1661-1665',
    'genre' => 'Tragédie',
    'play' => 'corneillep_othon',
    'titleId' => 'Othon',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'ALBIN' => 'ALBIN',
      'OTHON' => 'OTHON',
      'VINIUS' => 'VINIUS',
      'PLAUTINE' => 'PLAUTINE',
      'FLAVIE' => 'FLAVIE',
      'MARTIAN' => 'MARTIAN',
      'LACUS' => 'LACUS',
      'CAMILLE' => 'CAMILLE',
      'ALBIANE' => 'ALBIANE',
      'GALBA' => 'GALBA',
      'RUTILE' => 'RUTILE',
      'ATTICUS' => 'ATTICUS',
    ),
  ),
  'corneillep_oedipe' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Oedipe',
    'date' => 1659,
    'lustrum' => '1656-1660',
    'genre' => 'Tragédie',
    'play' => 'corneillep_oedipe',
    'titleId' => 'Oedipe',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'THESEE' => 'THÉSÉE',
      'DIRCE' => 'DIRCÉ',
      'MEGARE' => 'MÉGARE',
      'OEDIPE' => 'OEDIPE',
      'CLEANTE' => 'CLÉANTE',
      'JOCASTE' => 'JOCASTE',
      'NERINE' => 'NÉRINE',
      'DYMAS' => 'DYMAS',
      'PHORBAS' => 'PHORBAS',
      'PAGE' => 'UN PAGE',
      'IPHICRATE' => 'IPHICRATE',
    ),
  ),
  'corneillep_nicomede' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Nicomède',
    'date' => 1650,
    'lustrum' => '1646-1650',
    'genre' => 'Tragédie',
    'play' => 'corneillep_nicomede',
    'titleId' => 'Nicomede',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'LAODICE' => 'LAODICE',
      'NICOMEDE' => 'NICOMÈDE',
      'ATTALE' => 'ATTALE',
      'ARSINOE' => 'ARSINOÉ',
      'CLEONE' => 'CLÉONE',
      'PRUSIAS' => 'PRUSIAS',
      'ARASPE' => 'ARASPE',
      'FLAMINIUS' => 'FLAMINIUS',
    ),
  ),
  'corneillep_mortpompee' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'La Mort de Pompée',
    'date' => 1644,
    'lustrum' => '1641-1645',
    'genre' => 'Tragédie',
    'play' => 'corneillep_mortpompee',
    'titleId' => 'LaMortdePompee',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'PTOLEMEE' => 'PTOLÉMÉE',
      'PHOTIN' => 'PHOTIN',
      'ACHILLAS' => 'ACHILLAS',
      'SEPTIME' => 'SEPTIME',
      'CLEOPATRE' => 'CLÉOPATRE',
      'CHARMION' => 'CHARMION',
      'ACHOREE' => 'ACHORÉE',
      'CESAR' => 'JULES CÉSAR',
      'ANTOINE' => 'MARC ANTOINE',
      'CORNELIE' => 'CORNÉLIE',
      'PHILIPPE' => 'PHILIPPE',
    ),
  ),
  'corneillep_menteur' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Le Menteur',
    'date' => 1644,
    'lustrum' => '1641-1645',
    'genre' => 'Comédie',
    'play' => 'corneillep_menteur',
    'titleId' => 'LeMenteur',
    'genreId' => 'Comedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'DORANTE' => 'DORANTE',
      'CLITON' => 'CLITON',
      'CLARICE' => 'CLARICE',
      'LUCRECE' => 'LUCRÈCE',
      'ISABELLE' => 'ISABELLE',
      'PHILISTE' => 'PHILISTE',
      'ALCIPPE' => 'ALCIPPE',
      'GERONTE' => 'GÉRONTE',
      'SABINE' => 'SABINE',
      'LYCAS' => 'LYCAS',
    ),
  ),
  'corneillep_melite' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Mélite',
    'date' => 1630,
    'lustrum' => '1626-1630',
    'genre' => 'Comédie',
    'play' => 'corneillep_melite',
    'titleId' => 'Melite',
    'genreId' => 'Comedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'ERASTE' => 'ERASTE',
      'TIRCIS' => 'TIRCIS',
      'MELITE' => 'MÉLITE',
      'PHILANDRE' => 'PHILANDRE',
      'CHLORIS' => 'CHLORIS',
      'CLITON' => 'CLITON',
      'NOURRICE' => 'LA NOURRICE DE MÉLITE',
      'LISIS' => 'LISIS',
    ),
  ),
  'corneillep_medee39' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Médée',
    'date' => 1635,
    'lustrum' => '1631-1635',
    'genre' => 'Tragédie',
    'play' => 'corneillep_medee39',
    'titleId' => 'Medee',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'POLLUX' => 'POLLUX',
      'JASON' => 'JASON',
      'CREUSE' => 'CRÉUSE',
      'CLEONE' => 'CLÉONE',
      'MEDEE' => 'MÉDÉE',
      'NERINE' => 'NÉRINE',
      'CREON' => 'CRÉON',
      'AEGEE' => 'AEGÉE',
      'THEUDAS' => 'THEUDAS',
    ),
  ),
  'corneillep_illusioncomique' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'L\'Illusion comique',
    'date' => 1636,
    'lustrum' => '1636-1640',
    'genre' => 'Comédie',
    'play' => 'corneillep_illusioncomique',
    'titleId' => 'LIllusioncomique',
    'genreId' => 'Comedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'DORANTE' => 'DORANTE',
      'PRIDAMANT' => 'PRIDAMANT',
      'ALCANDRE' => 'ALCANDRE',
      'CLINDOR' => 'CLINDOR',
      'MATAMORE' => 'MATAMORE',
      'ADRASTE' => 'ADRASTE',
      'ISABELLE' => 'ISABELLE',
      'PAGE' => 'PAGE du CAPITAN',
      'LYSE' => 'LYSE',
      'GERONTE' => 'GÉRONTE',
      'GEOLIER' => 'LE GEÔLIER',
      'ERASTE' => 'ERASTE',
    ),
  ),
  'corneillep_horace' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Horace',
    'date' => 1640,
    'lustrum' => '1636-1640',
    'genre' => 'Tragédie',
    'play' => 'corneillep_horace',
    'titleId' => 'Horace',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'SABINE' => 'SABINE',
      'JULIE' => 'JULIE',
      'CAMILLE' => 'CAMILLE',
      'CURIACE' => 'CURIACE',
      'HORACE' => 'HORACE',
      'FLAVIAN' => 'FLAVIAN',
      'VIEILHORACE' => 'Le vieil HORACE',
      'VALERE' => 'VALÈRE',
      'PROCULE' => 'PROCULE',
      'TULLE' => 'TULLE',
    ),
  ),
  'corneillep_heraclius' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Héraclius',
    'date' => 1646,
    'lustrum' => '1646-1650',
    'genre' => 'Tragédie',
    'play' => 'corneillep_heraclius',
    'titleId' => 'Heraclius',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'PHOCAS' => 'PHOCAS',
      'CRISPE' => 'CRISPE',
      'PULCHERIE' => 'PULCHÉRIE',
      'HERACLIUS' => 'HÉRACLIUS',
      'MARTIAN' => 'MARTIAN',
      'LEONTINE' => 'LÉONTINE',
      'EUDOXE' => 'EUDOXE',
      'PAGE' => 'UN PAGE',
      'EXUPERE' => 'EXUPÈRE',
      'AMYNTAS' => 'AMYNTAS',
    ),
  ),
  'corneillep_galeriedupalais' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'La Galerie du palais',
    'date' => 1633,
    'lustrum' => '1631-1635',
    'genre' => 'Comédie',
    'play' => 'corneillep_galeriedupalais',
    'titleId' => 'LaGaleriedupalais',
    'genreId' => 'Comedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'ARONTE' => 'ARONTE',
      'FLORICE' => 'FLORICE',
      'PLEIRANTE' => 'PLEIRANTE',
      'CELIDEE' => 'CÉLIDÉE',
      'LINGERE' => 'La Lingère du palais',
      'LIBRAIRE' => 'Le Libraire du palais ',
      'DORIMANT' => 'DORIMANT',
      'HIPPOLYTE' => 'HIPPOLYTE',
      'CLEANTE' => 'CLÉANTE',
      'LYSANDRE' => 'LYSANDRE',
      'MERCIER' => 'Le Mercier du palais',
      'CHRYSANTE' => 'CHRYSANTE',
    ),
  ),
  'corneillep_donsanche' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Don Sanche d\'Aragon',
    'date' => 1649,
    'lustrum' => '1646-1650',
    'genre' => 'Comédie héroïque',
    'play' => 'corneillep_donsanche',
    'titleId' => 'DonSanchedAragon',
    'genreId' => 'Comedieheroique',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'LEONOR' => 'DONA LÉONOR',
      'ELVIRE' => 'DONA ELVIRE',
      'ISABELLE' => 'DONA ISABELLE',
      'BLANCHE' => 'BLANCHE',
      'LOPE' => 'DON LOPE DE GUSMAN',
      'MANRIQUE' => 'DON MANRIQUE DE LARE',
      'ALVAR' => 'DON ALVAR DE LUNE',
      'CARLOS' => 'CARLOS',
      'GARDE' => 'Un garde',
      'RAYMOND' => 'DON RAYMOND DE MONCADE',
    ),
  ),
  'corneillep_clitandre' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Clitandre',
    'date' => 1631,
    'lustrum' => '1631-1635',
    'genre' => 'Tragédie',
    'play' => 'corneillep_clitandre',
    'titleId' => 'Clitandre',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'CALISTE' => 'CALISTE',
      'ROSIDOR' => 'ROSIDOR',
      'LYSARQUE' => 'LYSARQUE',
      'DORISE' => 'DORISE',
      'GERONTE' => 'GÉRONTE',
      'PYMANTE' => 'PYMANTE',
      'LYCASTE' => 'LYCASTE',
      'CLEON' => 'CLÉON',
      'ARCHER1' => 'PREMIER ARCHER',
      'ARCHER2' => 'SECOND ARCHER',
      'FLORIDAN' => 'FLORIDAN',
      'CLITANDRE' => 'CLITANDRE',
      'ALCANDRE' => 'ALCANDRE',
      'GEOLIER' => 'LE GEÔLIER',
      'VENEUR1' => 'PREMIER VENEUR',
      'VENEUR2' => 'SECOND VENEUR',
    ),
  ),
  'corneillep_cinna' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Cinna',
    'date' => 1642,
    'lustrum' => '1641-1645',
    'genre' => 'Tragédie',
    'play' => 'corneillep_cinna',
    'titleId' => 'Cinna',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'EMILIE' => 'ÉMILIE',
      'FULVIE' => 'FULVIE',
      'CINNA' => 'CINNA',
      'EVANDRE' => 'ÉVANDRE',
      'AUGUSTE' => 'OCTAVE-CÉSAR AUGUSTE',
      'MAXIME' => 'MAXIME',
      'EUPHORBE' => 'EUPHORBE',
      'POLYCLETE' => 'POLYCLÈTE',
      'LIVIE' => 'LIVIE',
    ),
  ),
  'corneillep_cid37' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Le Cid',
    'date' => 1637,
    'lustrum' => '1636-1640',
    'genre' => 'Tragi-comédie',
    'play' => 'corneillep_cid37',
    'titleId' => 'LeCid',
    'genreId' => 'Tragi-comedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'ELVIRE' => 'ELVIRE',
      'COMTE' => 'DON GOMES',
      'CHIMENE' => 'CHIMÈNE',
      'INFANTE' => 'DONA URRAQUE',
      'LEONOR' => 'LÉONOR',
      'PAGE' => 'UN PAGE',
      'DIEGUE' => 'DON DIÈGUE',
      'RODRIGUE' => 'DON RODRIGUE',
      'ARIAS' => 'DON ARIAS',
      'FERNAND' => 'DON FERNAND',
      'SANCHE' => 'DON SANCHE',
      'ALONSE' => 'DON ALONSE',
    ),
  ),
  'corneillep_attila' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Attila',
    'date' => 1667,
    'lustrum' => '1666-1670',
    'genre' => 'Tragédie',
    'play' => 'corneillep_attila',
    'titleId' => 'Attila',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'ATTILA' => 'ATTILA',
      'OCTAR' => 'OCTAR',
      'ARDARIC' => 'ARDARIC',
      'VALAMIR' => 'VALAMIR',
      'FLAVIE' => 'FLAVIE',
      'HONORIE' => 'HONORIE',
      'ILDIONE' => 'ILDIONE',
    ),
  ),
  'corneillep_andromede' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Andromède',
    'date' => 1650,
    'lustrum' => '1646-1650',
    'genre' => 'Tragédie',
    'play' => 'corneillep_andromede',
    'titleId' => 'Andromede',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'CASSIOPE' => 'CASSIOPE',
      'PERSEE' => 'PERSÉE',
      'SOLEIL' => '',
      'CEPHEE' => 'CÉPHÉE',
      'PHINEE' => 'PHINÉE',
      'SUITE' => 'Suite du roi',
      'CHOEUR' => 'Choeur du peuple',
      'VENUS' => 'VÉNUS',
      'ANDROMEDE' => 'ANDROMÈDE',
      'AGLANTE' => 'AGLANTE',
      'CEPHALIE' => 'CÉPHALIE',
      'PAGE' => 'Un page de Phinée',
      'LIRIOPE' => 'LIRIOPE',
      'PAGE LIRIOPE' => '',
      'TIMANTE' => 'TIMANTE',
      'EOLE' => 'ÉOLE',
      'HUITVENTS' => 'HUIT VENTS',
      'VOIX' => 'Une voix',
      'CYMODOCE' => 'CYMODOCE',
      'EPHYRE' => 'EPHYRE',
      'CYDIPPE' => 'CYDIPPE',
      'NEREIDES' => 'NÉRÉIDES',
      'NEPTUNE' => 'NEPTUNE',
      'AMMON' => 'AMMON',
      'JUNON' => 'JUNON',
      'PHORBAS' => 'PHORBAS',
      'MERCURE' => 'MERCURE',
      'JUPITER' => 'JUPITER',
    ),
  ),
  'corneillep_agesilas' => 
  array (
    'author' => 'Corneille, Pierre',
    'title' => 'Agésilas',
    'date' => 1666,
    'lustrum' => '1666-1670',
    'genre' => 'Tragédie',
    'play' => 'corneillep_agesilas',
    'titleId' => 'Agesilas',
    'genreId' => 'Tragedie',
    'authorId' => 'CorneillePierre',
    'roles' => 
    array (
      'AGLATIDE' => 'AGLATIDE',
      'ELPINICE' => 'ELPINICE',
      'SPITRIDATE' => 'SPITRIDATE',
      'COTYS' => 'COTYS',
      'MANDANE' => 'MANDANE',
      'LYSANDER' => 'LYSANDER',
      'CLEON' => 'CLÉON',
      'AGESILAS' => 'AGÉSILAS',
      'XENOCLES' => 'XENOCLES',
    ),
  ),
); ?>