<?php $haystack[10]["CG"] = array (
  'corneillep_veuve34_III01' => 
  array (
    'pattern' => 
    array (
      '#PHILISTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#ALCIDON' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
      '#CELIDAN' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
      '#CLARICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#DORIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 1,
      ),
      '#GERON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LYCAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LISTOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_veuve34',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Veuve',
      'date' => 1632,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaVeuve',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ALCIDON-CÉLIDAN/ALCIDON/PHILISTE-ALCIDON/CHRYSANTE-DORIS/CHRYSANTE-GÉRON/PHILISTE-CHRYSANTE-GÉRON-LYCAS/PHILISTE-CHRYSANTE-LYCAS/CLARICE/ALCIDON-CÉLIDAN-CLARICE-LA NOURRICE de Clarice/LA NOURRICE de Clarice-POLYMAS-DORASTE-LISTOR',
    ),
  ),
  'corneillep_suivante_III01' => 
  array (
    'pattern' => 
    array (
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CLARIMOND' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'FLORAME/CLARIMOND-DAPHNIS/CLARIMOND/CLARIMOND//GÉRASTE/GÉRASTE/DAPHNIS/FLORAME-DAPHNIS/DAPHNIS',
    ),
  ),
  'corneillep_suivante_III02' => 
  array (
    'pattern' => 
    array (
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CLARIMOND' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLARIMOND-DAPHNIS/CLARIMOND/CLARIMOND//GÉRASTE/GÉRASTE/DAPHNIS/FLORAME-DAPHNIS/DAPHNIS/',
    ),
  ),
  'corneillep_melite_IV01' => 
  array (
    'pattern' => 
    array (
      '#ERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#PHILANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#MELITE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CHLORIS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#LISIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#CLITON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_melite',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'Mélite',
      'date' => 1630,
      'lustrum' => '1626-1630',
      'genre' => 'Comédie',
      'titleId' => 'Melite',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'MÉLITE-LA NOURRICE DE MÉLITE/MÉLITE-CHLORIS/MÉLITE-CHLORIS-LISIS/MÉLITE-CHLORIS-LISIS-CLITON-LA NOURRICE DE MÉLITE/ERASTE/ERASTE-CLITON/PHILANDRE/ERASTE-PHILANDRE/ERASTE/CHLORIS-LISIS',
    ),
  ),
  'corneillep_illusioncomique_II01' => 
  array (
    'pattern' => 
    array (
      '#PRIDAMANT' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#PAGE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '2',
      'scene' => '1',
      'sceneId' => 'II01',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ALCANDRE-PRIDAMANT/MATAMORE-CLINDOR/ADRASTE-ISABELLE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR-ISABELLE-PAGE du CAPITAN/CLINDOR-ISABELLE/CLINDOR-ADRASTE/ADRASTE-LYSE/LYSE/ALCANDRE-PRIDAMANT',
    ),
  ),
  'corneillep_illusioncomique_III01' => 
  array (
    'pattern' => 
    array (
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 1,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 1,
      ),
      '#GERONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
        9 => 1,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'GÉRONTE-ISABELLE/GÉRONTE/MATAMORE-CLINDOR-GÉRONTE/MATAMORE-CLINDOR/CLINDOR-LYSE/LYSE/MATAMORE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR/MATAMORE-CLINDOR-ISABELLE',
    ),
  ),
  'corneillep_illusioncomique_III02' => 
  array (
    'pattern' => 
    array (
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 1,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 1,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#GERONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 1,
        9 => 1,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'GÉRONTE/MATAMORE-CLINDOR-GÉRONTE/MATAMORE-CLINDOR/CLINDOR-LYSE/LYSE/MATAMORE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR-ADRASTE-GÉRONTE-ISABELLE-LYSE',
    ),
  ),
  'corneillep_illusioncomique_III03' => 
  array (
    'pattern' => 
    array (
      '#PRIDAMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#CLINDOR' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
      '#GERONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '3',
      'sceneId' => 'III03',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'MATAMORE-CLINDOR-GÉRONTE/MATAMORE-CLINDOR/CLINDOR-LYSE/LYSE/MATAMORE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR-ADRASTE-GÉRONTE-ISABELLE-LYSE/ALCANDRE-PRIDAMANT',
    ),
  ),
  'corneillep_illusioncomique_IV01' => 
  array (
    'pattern' => 
    array (
      '#PRIDAMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
      '#GEOLIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ISABELLE/ISABELLE-LYSE/LYSE/MATAMORE-ISABELLE-LYSE/ISABELLE-LYSE/ISABELLE-LYSE-LE GEÔLIER/CLINDOR/CLINDOR-LE GEÔLIER/CLINDOR-ISABELLE-LYSE-LE GEÔLIER/ALCANDRE-PRIDAMANT',
    ),
  ),
  'corneillep_galeriedupalais_I01' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '1',
      'scene' => '1',
      'sceneId' => 'I01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE-ARONTE/Le Libraire du palais -La Lingère du palais/DORIMANT-Le Libraire du palais /DORIMANT-HIPPOLYTE-CLÉANTE-Le Libraire du palais -La Lingère du palais/LYSANDRE-DORIMANT-Le Libraire du palais -Le Mercier du palais/LYSANDRE-DORIMANT/LYSANDRE-DORIMANT-CLÉANTE/HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_I02' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 1,
      ),
      '#ARONTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '1',
      'scene' => '2',
      'sceneId' => 'I02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'PLEIRANTE-CÉLIDÉE/CÉLIDÉE-ARONTE/Le Libraire du palais -La Lingère du palais/DORIMANT-Le Libraire du palais /DORIMANT-HIPPOLYTE-CLÉANTE-Le Libraire du palais -La Lingère du palais/LYSANDRE-DORIMANT-Le Libraire du palais -Le Mercier du palais/LYSANDRE-DORIMANT/LYSANDRE-DORIMANT-CLÉANTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_III01' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'LYSANDRE-ARONTE/ARONTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/LYSANDRE-CÉLIDÉE-HIPPOLYTE/LYSANDRE-HIPPOLYTE/PLEIRANTE-CHRYSANTE/CHRYSANTE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_III02' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/LYSANDRE-CÉLIDÉE-HIPPOLYTE/LYSANDRE-HIPPOLYTE/PLEIRANTE-CHRYSANTE/CHRYSANTE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE/DORIMANT-CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_III03' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 1,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '3',
      'sceneId' => 'III03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/LYSANDRE-CÉLIDÉE-HIPPOLYTE/LYSANDRE-HIPPOLYTE/PLEIRANTE-CHRYSANTE/CHRYSANTE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE/DORIMANT-CÉLIDÉE/DORIMANT',
    ),
  ),
  'corneillep_galeriedupalais_IV01' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 1,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
        9 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'HIPPOLYTE-ARONTE/DORIMANT-CÉLIDÉE-ARONTE/DORIMANT-CÉLIDÉE/LYSANDRE-ARONTE/LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_IV02' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 1,
        9 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '2',
      'sceneId' => 'IV02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DORIMANT-CÉLIDÉE-ARONTE/DORIMANT-CÉLIDÉE/LYSANDRE-ARONTE/LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_IV03' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '3',
      'sceneId' => 'IV03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DORIMANT-CÉLIDÉE/LYSANDRE-ARONTE/LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE/Le Mercier du palais-La Lingère du palais',
    ),
  ),
  'corneillep_galeriedupalais_IV04' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
        9 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '4',
      'sceneId' => 'IV04',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'LYSANDRE-ARONTE/LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE/Le Mercier du palais-La Lingère du palais/CLÉANTE-Le Libraire du palais -Le Mercier du palais-La Lingère du palais',
    ),
  ),
  'corneillep_galeriedupalais_IV05' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
        9 => 1,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
        9 => 0,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
        9 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '5',
      'sceneId' => 'IV05',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE/Le Mercier du palais-La Lingère du palais/CLÉANTE-Le Libraire du palais -Le Mercier du palais-La Lingère du palais/ARONTE-Le Mercier du palais-La Lingère du palais',
    ),
  ),
); ?>