<?php $haystack[9]["G"] = array (
  'corneillep_veuve34_III01' => 
  array (
    'pattern' => 
    array (
      '#PHILISTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#ALCIDON' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#NOURRICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#DORIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#GERON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLARICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CELIDAN' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LYCAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_veuve34',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Veuve',
      'date' => 1632,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaVeuve',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ALCIDON-CÉLIDAN/ALCIDON/PHILISTE-ALCIDON/CHRYSANTE-DORIS/CHRYSANTE-GÉRON/PHILISTE-CHRYSANTE-GÉRON-LYCAS/PHILISTE-CHRYSANTE-LYCAS/CLARICE/ALCIDON-LA NOURRICE de Clarice-CLARICE-CÉLIDAN',
    ),
  ),
  'corneillep_veuve34_III02' => 
  array (
    'pattern' => 
    array (
      '#PHILISTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ALCIDON' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#GERON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLARICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#CELIDAN' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#LYCAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LISTOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_veuve34',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Veuve',
      'date' => 1632,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaVeuve',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ALCIDON/PHILISTE-ALCIDON/CHRYSANTE-DORIS/CHRYSANTE-GÉRON/PHILISTE-CHRYSANTE-GÉRON-LYCAS/PHILISTE-CHRYSANTE-LYCAS/CLARICE/ALCIDON-LA NOURRICE de Clarice-CLARICE-CÉLIDAN/LA NOURRICE de Clarice-POLYMAS-DORASTE-LISTOR',
    ),
  ),
  'corneillep_veuve34_IV01' => 
  array (
    'pattern' => 
    array (
      '#PHILISTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ALCIDON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CELIDAN' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LYCAS' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LISTOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_veuve34',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Veuve',
      'date' => 1632,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaVeuve',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'PHILISTE-LYCAS/PHILISTE-POLYMAS-DORASTE-LISTOR/PHILISTE-ALCIDON-CÉLIDAN/ALCIDON-CÉLIDAN/CÉLIDAN/LA NOURRICE de Clarice-CÉLIDAN/CÉLIDAN/ALCIDON-DORIS/DORIS',
    ),
  ),
  'corneillep_veuve34_V01' => 
  array (
    'pattern' => 
    array (
      '#PHILISTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ALCIDON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#DORIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CLARICE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#CELIDAN' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_veuve34',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Veuve',
      'date' => 1632,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaVeuve',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLARICE-CÉLIDAN/CÉLIDAN/ALCIDON-CÉLIDAN/PHILISTE-CHRYSANTE-DORIS/PHILISTE-CHRYSANTE-DORIS-CÉLIDAN/CHRYSANTE-DORIS-CÉLIDAN/PHILISTE-CLARICE/PHILISTE-CHRYSANTE-DORIS-CLARICE-CÉLIDAN/PHILISTE-ALCIDON-CHRYSANTE-DORIS-CLARICE-CÉLIDAN',
    ),
  ),
  'corneillep_theodore_V01' => 
  array (
    'pattern' => 
    array (
      '#PLACIDE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLEOBULE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#MARCELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#STEPHANIE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#VALENS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#THEODORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PAULIN' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LYCANTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DIDYME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_theodore',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'Théodore',
      'date' => 1645,
      'lustrum' => '1641-1645',
      'genre' => 'Tragédie',
      'titleId' => 'Theodore',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLÉOBULE-PAULIN/CLÉOBULE-LYCANTE/CLÉOBULE-DIDYME/CLÉOBULE-THÉODORE-DIDYME/THÉODORE-DIDYME/MARCELLE-THÉODORE-PAULIN-DIDYME/VALENS-PAULIN/STÉPHANIE-VALENS/PLACIDE-CLÉOBULE-VALENS',
    ),
  ),
  'corneillep_suivante_I01' => 
  array (
    'pattern' => 
    array (
      '#DAMON' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#THEANTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#AMARANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '1',
      'scene' => '1',
      'sceneId' => 'I01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DAMON-THÉANTE/THÉANTE/THÉANTE-FLORAME/THÉANTE-FLORAME-AMARANTE/FLORAME-AMARANTE/THÉANTE-DAPHNIS/THÉANTE-FLORAME-DAPHNIS/AMARANTE-DAPHNIS/AMARANTE',
    ),
  ),
  'corneillep_suivante_II01' => 
  array (
    'pattern' => 
    array (
      '#DAMON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#THEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#AMARANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#GERASTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '2',
      'scene' => '1',
      'sceneId' => 'II01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CÉLIE-GÉRASTE/FLORAME/FLORAME-AMARANTE/FLORAME-AMARANTE-DAPHNIS/FLORAME-DAPHNIS/DAPHNIS/AMARANTE-DAPHNIS/THÉANTE-AMARANTE/DAMON-THÉANTE',
    ),
  ),
  'corneillep_suivante_III01' => 
  array (
    'pattern' => 
    array (
      '#FLORAME' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#AMARANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CELIE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#CLARIMOND' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'FLORAME-CÉLIE/DAPHNIS-CLARIMOND/CLARIMOND/AMARANTE-CLARIMOND/AMARANTE/AMARANTE-GÉRASTE/GÉRASTE/DAPHNIS/FLORAME-DAPHNIS',
    ),
  ),
  'corneillep_suivante_III02' => 
  array (
    'pattern' => 
    array (
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#AMARANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#DAPHNIS' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLARIMOND' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DAPHNIS-CLARIMOND/CLARIMOND/AMARANTE-CLARIMOND/AMARANTE/AMARANTE-GÉRASTE/GÉRASTE/DAPHNIS/FLORAME-DAPHNIS/AMARANTE-DAPHNIS',
    ),
  ),
  'corneillep_suivante_III03' => 
  array (
    'pattern' => 
    array (
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#AMARANTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLARIMOND' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '3',
      'scene' => '3',
      'sceneId' => 'III03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLARIMOND/AMARANTE-CLARIMOND/AMARANTE/AMARANTE-GÉRASTE/GÉRASTE/DAPHNIS/FLORAME-DAPHNIS/AMARANTE-DAPHNIS/AMARANTE',
    ),
  ),
  'corneillep_suivante_IV01' => 
  array (
    'pattern' => 
    array (
      '#THEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#AMARANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#CELIE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLEON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DAPHNIS/DAPHNIS-GÉRASTE/AMARANTE-GÉRASTE/AMARANTE/DAMON-FLORAME-CLÉON/THÉANTE-FLORAME/FLORAME-DAPHNIS/FLORAME/FLORAME-CÉLIE',
    ),
  ),
  'corneillep_suivante_V01' => 
  array (
    'pattern' => 
    array (
      '#THEANTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#AMARANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#CELIE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#POLEMON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DAMON-THÉANTE/FLORAME/FLORAME-AMARANTE/AMARANTE/GÉRASTE-POLÉMON/CÉLIE-GÉRASTE/DAPHNIS-GÉRASTE/FLORAME-AMARANTE-DAPHNIS-CÉLIE-GÉRASTE/AMARANTE',
    ),
  ),
  'corneillep_oedipe_V01' => 
  array (
    'pattern' => 
    array (
      '#THESEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#DIRCE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#OEDIPE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#NERINE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DYMAS' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#PHORBAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PAGE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#IPHICRATE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_oedipe',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'Oedipe',
      'date' => 1659,
      'lustrum' => '1656-1660',
      'genre' => 'Tragédie',
      'titleId' => 'Oedipe',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'OEDIPE-DYMAS-UN PAGE/OEDIPE-IPHICRATE/OEDIPE-PHORBAS-IPHICRATE/OEDIPE-IPHICRATE/DIRCÉ-OEDIPE-IPHICRATE/THÉSÉE-DIRCÉ-OEDIPE-IPHICRATE/THÉSÉE-DIRCÉ/THÉSÉE-DIRCÉ-NÉRINE/THÉSÉE-DIRCÉ-CLÉANTE-NÉRINE-DYMAS',
    ),
  ),
  'corneillep_nicomede_V01' => 
  array (
    'pattern' => 
    array (
      '#LAODICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#NICOMEDE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#ATTALE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ARSINOE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#CLEONE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#PRUSIAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#ARASPE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLAMINIUS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_nicomede',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'Nicomède',
      'date' => 1650,
      'lustrum' => '1646-1650',
      'genre' => 'Tragédie',
      'titleId' => 'Nicomede',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ATTALE-ARSINOÉ/ATTALE-ARSINOÉ-FLAMINIUS/ATTALE-ARSINOÉ-PRUSIAS-FLAMINIUS/ATTALE-ARSINOÉ-CLÉONE-PRUSIAS-FLAMINIUS/ATTALE-ARSINOÉ-CLÉONE-PRUSIAS-ARASPE-FLAMINIUS/LAODICE-ARSINOÉ-CLÉONE/LAODICE-ATTALE-ARSINOÉ-CLÉONE/LAODICE-ATTALE-ARSINOÉ-CLÉONE-PRUSIAS-FLAMINIUS/LAODICE-NICOMÈDE-ATTALE-ARSINOÉ-CLÉONE-PRUSIAS-FLAMINIUS',
    ),
  ),
  'corneillep_menteur_IV01' => 
  array (
    'pattern' => 
    array (
      '#DORANTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLITON' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#CLARICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LUCRECE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#ALCIPPE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#GERONTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#SABINE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_menteur',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'Le Menteur',
      'date' => 1644,
      'lustrum' => '1641-1645',
      'genre' => 'Comédie',
      'titleId' => 'LeMenteur',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DORANTE-CLITON/DORANTE-CLITON-ALCIPPE/DORANTE-CLITON/DORANTE-CLITON-GÉRONTE/DORANTE-CLITON/DORANTE-CLITON-SABINE/CLITON-SABINE/LUCRÈCE-SABINE/CLARICE-LUCRÈCE-SABINE',
    ),
  ),
  'corneillep_melite_IV01' => 
  array (
    'pattern' => 
    array (
      '#ERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#MELITE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PHILANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#CHLORIS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLITON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LISIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_melite',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'Mélite',
      'date' => 1630,
      'lustrum' => '1626-1630',
      'genre' => 'Comédie',
      'titleId' => 'Melite',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'MÉLITE-LA NOURRICE DE MÉLITE/MÉLITE-CHLORIS/MÉLITE-CHLORIS-LISIS/MÉLITE-CHLORIS-CLITON-LA NOURRICE DE MÉLITE-LISIS/ERASTE/ERASTE-CLITON/PHILANDRE/ERASTE-PHILANDRE/ERASTE',
    ),
  ),
  'corneillep_melite_IV02' => 
  array (
    'pattern' => 
    array (
      '#ERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#MELITE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PHILANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#CHLORIS' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLITON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LISIS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_melite',
      'act' => '4',
      'scene' => '2',
      'sceneId' => 'IV02',
      'author' => 'Corneille, Pierre',
      'title' => 'Mélite',
      'date' => 1630,
      'lustrum' => '1626-1630',
      'genre' => 'Comédie',
      'titleId' => 'Melite',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'MÉLITE-CHLORIS/MÉLITE-CHLORIS-LISIS/MÉLITE-CHLORIS-CLITON-LA NOURRICE DE MÉLITE-LISIS/ERASTE/ERASTE-CLITON/PHILANDRE/ERASTE-PHILANDRE/ERASTE/CHLORIS-LISIS',
    ),
  ),
  'corneillep_illusioncomique_II01' => 
  array (
    'pattern' => 
    array (
      '#ALCANDRE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PAGE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '2',
      'scene' => '1',
      'sceneId' => 'II01',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'PRIDAMANT-ALCANDRE/CLINDOR-MATAMORE/ADRASTE-ISABELLE/CLINDOR-MATAMORE-ISABELLE/CLINDOR-MATAMORE-ISABELLE-PAGE du CAPITAN/CLINDOR-ISABELLE/CLINDOR-ADRASTE/ADRASTE-LYSE/LYSE',
    ),
  ),
  'corneillep_illusioncomique_II02' => 
  array (
    'pattern' => 
    array (
      '#ALCANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLINDOR' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#MATAMORE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PAGE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '2',
      'scene' => '2',
      'sceneId' => 'II02',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLINDOR-MATAMORE/ADRASTE-ISABELLE/CLINDOR-MATAMORE-ISABELLE/CLINDOR-MATAMORE-ISABELLE-PAGE du CAPITAN/CLINDOR-ISABELLE/CLINDOR-ADRASTE/ADRASTE-LYSE/LYSE/PRIDAMANT-ALCANDRE',
    ),
  ),
  'corneillep_illusioncomique_III01' => 
  array (
    'pattern' => 
    array (
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ISABELLE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#GERONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ISABELLE-GÉRONTE/GÉRONTE/CLINDOR-MATAMORE-GÉRONTE/CLINDOR-MATAMORE/CLINDOR-LYSE/LYSE/MATAMORE/CLINDOR-MATAMORE-ISABELLE/CLINDOR-MATAMORE',
    ),
  ),
  'corneillep_illusioncomique_III02' => 
  array (
    'pattern' => 
    array (
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 1,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#GERONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'GÉRONTE/CLINDOR-MATAMORE-GÉRONTE/CLINDOR-MATAMORE/CLINDOR-LYSE/LYSE/MATAMORE/CLINDOR-MATAMORE-ISABELLE/CLINDOR-MATAMORE/CLINDOR-MATAMORE-ISABELLE',
    ),
  ),
  'corneillep_illusioncomique_III03' => 
  array (
    'pattern' => 
    array (
      '#CLINDOR' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#GERONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '3',
      'sceneId' => 'III03',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLINDOR-MATAMORE-GÉRONTE/CLINDOR-MATAMORE/CLINDOR-LYSE/LYSE/MATAMORE/CLINDOR-MATAMORE-ISABELLE/CLINDOR-MATAMORE/CLINDOR-MATAMORE-ISABELLE/CLINDOR-MATAMORE-ADRASTE-ISABELLE-LYSE-GÉRONTE',
    ),
  ),
  'corneillep_illusioncomique_III04' => 
  array (
    'pattern' => 
    array (
      '#ALCANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLINDOR' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#MATAMORE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#GERONTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '4',
      'sceneId' => 'III04',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLINDOR-MATAMORE/CLINDOR-LYSE/LYSE/MATAMORE/CLINDOR-MATAMORE-ISABELLE/CLINDOR-MATAMORE/CLINDOR-MATAMORE-ISABELLE/CLINDOR-MATAMORE-ADRASTE-ISABELLE-LYSE-GÉRONTE/PRIDAMANT-ALCANDRE',
    ),
  ),
  'corneillep_illusioncomique_IV01' => 
  array (
    'pattern' => 
    array (
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#GEOLIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ISABELLE/ISABELLE-LYSE/LYSE/MATAMORE-ISABELLE-LYSE/ISABELLE-LYSE/ISABELLE-LYSE-LE GEÔLIER/CLINDOR/CLINDOR-LE GEÔLIER/CLINDOR-ISABELLE-LYSE-LE GEÔLIER',
    ),
  ),
  'corneillep_illusioncomique_IV02' => 
  array (
    'pattern' => 
    array (
      '#ALCANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#GEOLIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '4',
      'scene' => '2',
      'sceneId' => 'IV02',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ISABELLE-LYSE/LYSE/MATAMORE-ISABELLE-LYSE/ISABELLE-LYSE/ISABELLE-LYSE-LE GEÔLIER/CLINDOR/CLINDOR-LE GEÔLIER/CLINDOR-ISABELLE-LYSE-LE GEÔLIER/PRIDAMANT-ALCANDRE',
    ),
  ),
  'corneillep_galeriedupalais_I01' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORICE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '1',
      'scene' => '1',
      'sceneId' => 'I01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE-FLORICE/PLEIRANTE-CÉLIDÉE/ARONTE-CÉLIDÉE/La Lingère du palais-Le Libraire du palais /Le Libraire du palais -DORIMANT/FLORICE-La Lingère du palais-Le Libraire du palais -DORIMANT-HIPPOLYTE-CLÉANTE/Le Libraire du palais -DORIMANT-LYSANDRE-Le Mercier du palais/DORIMANT-LYSANDRE/DORIMANT-CLÉANTE-LYSANDRE',
    ),
  ),
  'corneillep_galeriedupalais_I02' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '1',
      'scene' => '2',
      'sceneId' => 'I02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'PLEIRANTE-CÉLIDÉE/ARONTE-CÉLIDÉE/La Lingère du palais-Le Libraire du palais /Le Libraire du palais -DORIMANT/FLORICE-La Lingère du palais-Le Libraire du palais -DORIMANT-HIPPOLYTE-CLÉANTE/Le Libraire du palais -DORIMANT-LYSANDRE-Le Mercier du palais/DORIMANT-LYSANDRE/DORIMANT-CLÉANTE-LYSANDRE/FLORICE-HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_I03' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '1',
      'scene' => '3',
      'sceneId' => 'I03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE-CÉLIDÉE/La Lingère du palais-Le Libraire du palais /Le Libraire du palais -DORIMANT/FLORICE-La Lingère du palais-Le Libraire du palais -DORIMANT-HIPPOLYTE-CLÉANTE/Le Libraire du palais -DORIMANT-LYSANDRE-Le Mercier du palais/DORIMANT-LYSANDRE/DORIMANT-CLÉANTE-LYSANDRE/FLORICE-HIPPOLYTE/CÉLIDÉE-HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_II01' => 
  array (
    'pattern' => 
    array (
      '#FLORICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '2',
      'scene' => '1',
      'sceneId' => 'II01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DORIMANT-HIPPOLYTE/DORIMANT-HIPPOLYTE-LYSANDRE/DORIMANT-LYSANDRE/FLORICE-DORIMANT/FLORICE-HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/CÉLIDÉE/CÉLIDÉE-LYSANDRE/LYSANDRE',
    ),
  ),
  'corneillep_galeriedupalais_III01' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORICE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE-LYSANDRE/ARONTE-FLORICE/FLORICE-HIPPOLYTE/FLORICE-CÉLIDÉE-HIPPOLYTE/CÉLIDÉE-HIPPOLYTE-LYSANDRE/HIPPOLYTE-LYSANDRE/PLEIRANTE-CHRYSANTE/HIPPOLYTE-CHRYSANTE/FLORICE-HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_III02' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORICE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE-FLORICE/FLORICE-HIPPOLYTE/FLORICE-CÉLIDÉE-HIPPOLYTE/CÉLIDÉE-HIPPOLYTE-LYSANDRE/HIPPOLYTE-LYSANDRE/PLEIRANTE-CHRYSANTE/HIPPOLYTE-CHRYSANTE/FLORICE-HIPPOLYTE/CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_III03' => 
  array (
    'pattern' => 
    array (
      '#FLORICE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '3',
      'sceneId' => 'III03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'FLORICE-HIPPOLYTE/FLORICE-CÉLIDÉE-HIPPOLYTE/CÉLIDÉE-HIPPOLYTE-LYSANDRE/HIPPOLYTE-LYSANDRE/PLEIRANTE-CHRYSANTE/HIPPOLYTE-CHRYSANTE/FLORICE-HIPPOLYTE/CÉLIDÉE/CÉLIDÉE-DORIMANT',
    ),
  ),
  'corneillep_galeriedupalais_III04' => 
  array (
    'pattern' => 
    array (
      '#FLORICE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '4',
      'sceneId' => 'III04',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'FLORICE-CÉLIDÉE-HIPPOLYTE/CÉLIDÉE-HIPPOLYTE-LYSANDRE/HIPPOLYTE-LYSANDRE/PLEIRANTE-CHRYSANTE/HIPPOLYTE-CHRYSANTE/FLORICE-HIPPOLYTE/CÉLIDÉE/CÉLIDÉE-DORIMANT/FLORICE-DORIMANT',
    ),
  ),
  'corneillep_galeriedupalais_IV01' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE-HIPPOLYTE/ARONTE-CÉLIDÉE-DORIMANT/CÉLIDÉE-DORIMANT/ARONTE-LYSANDRE/LYSANDRE/HIPPOLYTE-LYSANDRE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_IV02' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 1,
      ),
      '#DORIMANT' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '2',
      'sceneId' => 'IV02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE-CÉLIDÉE-DORIMANT/CÉLIDÉE-DORIMANT/ARONTE-LYSANDRE/LYSANDRE/HIPPOLYTE-LYSANDRE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_IV03' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DORIMANT' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '3',
      'sceneId' => 'IV03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CÉLIDÉE-DORIMANT/ARONTE-LYSANDRE/LYSANDRE/HIPPOLYTE-LYSANDRE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_IV04' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '4',
      'sceneId' => 'IV04',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE-LYSANDRE/LYSANDRE/HIPPOLYTE-LYSANDRE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE/La Lingère du palais-Le Mercier du palais',
    ),
  ),
  'corneillep_galeriedupalais_IV05' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '5',
      'sceneId' => 'IV05',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'LYSANDRE/HIPPOLYTE-LYSANDRE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE/La Lingère du palais-Le Mercier du palais/FLORICE-La Lingère du palais-Le Libraire du palais -CLÉANTE-Le Mercier du palais',
    ),
  ),
  'corneillep_galeriedupalais_IV06' => 
  array (
    'pattern' => 
    array (
      '#ARONTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#FLORICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '6',
      'sceneId' => 'IV06',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'HIPPOLYTE-LYSANDRE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE/La Lingère du palais-Le Mercier du palais/FLORICE-La Lingère du palais-Le Libraire du palais -CLÉANTE-Le Mercier du palais/ARONTE-FLORICE-La Lingère du palais-Le Mercier du palais',
    ),
  ),
  'corneillep_clitandre_I01' => 
  array (
    'pattern' => 
    array (
      '#CALISTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#ROSIDOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LYSARQUE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#DORISE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#PYMANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LYCASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLEON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_clitandre',
      'act' => '1',
      'scene' => '1',
      'sceneId' => 'I01',
      'author' => 'Corneille, Pierre',
      'title' => 'Clitandre',
      'date' => 1631,
      'lustrum' => '1631-1635',
      'genre' => 'Tragédie',
      'titleId' => 'Clitandre',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CALISTE/ROSIDOR-LYSARQUE/CALISTE/CALISTE-DORISE/GÉRONTE-PYMANTE/GÉRONTE-PYMANTE-LYCASTE/LYSARQUE-CLÉON/CALISTE-DORISE/CALISTE-ROSIDOR-DORISE-GÉRONTE-PYMANTE-LYCASTE',
    ),
  ),
  'corneillep_agesilas_V01' => 
  array (
    'pattern' => 
    array (
      '#AGLATIDE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#SPITRIDATE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#COTYS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#MANDANE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LYSANDER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#AGESILAS' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#XENOCLES' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_agesilas',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'Agésilas',
      'date' => 1666,
      'lustrum' => '1666-1670',
      'genre' => 'Tragédie',
      'titleId' => 'Agesilas',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'AGÉSILAS-XENOCLES/SPITRIDATE-AGÉSILAS-XENOCLES/SPITRIDATE-MANDANE-AGÉSILAS-XENOCLES/MANDANE-AGÉSILAS-XENOCLES/AGÉSILAS-XENOCLES/LYSANDER-AGÉSILAS-XENOCLES/LYSANDER-AGÉSILAS/AGLATIDE-LYSANDER-AGÉSILAS-XENOCLES/AGLATIDE-ELPINICE-SPITRIDATE-COTYS-MANDANE-LYSANDER-AGÉSILAS-XENOCLES',
    ),
  ),
); ?>