<?php $haystack[9]["C"] = array (
  'corneillep_veuve34_III01' => 
  array (
    'pattern' => 
    array (
      '#PHILISTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#ALCIDON' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CELIDAN' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLARICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#DORIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#GERON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYCAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_veuve34',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Veuve',
      'date' => 1632,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaVeuve',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ALCIDON-CÉLIDAN/ALCIDON/PHILISTE-ALCIDON/CHRYSANTE-DORIS/CHRYSANTE-GÉRON/PHILISTE-CHRYSANTE-GÉRON-LYCAS/PHILISTE-CHRYSANTE-LYCAS/CLARICE/ALCIDON-CÉLIDAN-CLARICE-LA NOURRICE de Clarice',
    ),
  ),
  'corneillep_veuve34_III02' => 
  array (
    'pattern' => 
    array (
      '#PHILISTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ALCIDON' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#CELIDAN' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#CLARICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#GERON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYCAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#POLYMAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#DORASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LISTOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_veuve34',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Veuve',
      'date' => 1632,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaVeuve',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ALCIDON/PHILISTE-ALCIDON/CHRYSANTE-DORIS/CHRYSANTE-GÉRON/PHILISTE-CHRYSANTE-GÉRON-LYCAS/PHILISTE-CHRYSANTE-LYCAS/CLARICE/ALCIDON-CÉLIDAN-CLARICE-LA NOURRICE de Clarice/LA NOURRICE de Clarice-POLYMAS-DORASTE-LISTOR',
    ),
  ),
  'corneillep_veuve34_IV01' => 
  array (
    'pattern' => 
    array (
      '#PHILISTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ALCIDON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#CELIDAN' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#DORIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#NOURRICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYCAS' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#POLYMAS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORASTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LISTOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_veuve34',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Veuve',
      'date' => 1632,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaVeuve',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'PHILISTE-LYCAS/PHILISTE-POLYMAS-DORASTE-LISTOR/PHILISTE-ALCIDON-CÉLIDAN/ALCIDON-CÉLIDAN/CÉLIDAN/CÉLIDAN-LA NOURRICE de Clarice/CÉLIDAN/ALCIDON-DORIS/DORIS',
    ),
  ),
  'corneillep_veuve34_V01' => 
  array (
    'pattern' => 
    array (
      '#PHILISTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ALCIDON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CELIDAN' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CLARICE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DORIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_veuve34',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Veuve',
      'date' => 1632,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaVeuve',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CÉLIDAN-CLARICE/CÉLIDAN/ALCIDON-CÉLIDAN/PHILISTE-CHRYSANTE-DORIS/PHILISTE-CÉLIDAN-CHRYSANTE-DORIS/CÉLIDAN-CHRYSANTE-DORIS/PHILISTE-CLARICE/PHILISTE-CÉLIDAN-CLARICE-CHRYSANTE-DORIS/PHILISTE-ALCIDON-CÉLIDAN-CLARICE-CHRYSANTE-DORIS',
    ),
  ),
  'corneillep_theodore_V01' => 
  array (
    'pattern' => 
    array (
      '#VALENS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#PLACIDE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLEOBULE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#DIDYME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PAULIN' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LYCANTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#MARCELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#THEODORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#STEPHANIE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_theodore',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'Théodore',
      'date' => 1645,
      'lustrum' => '1641-1645',
      'genre' => 'Tragédie',
      'titleId' => 'Theodore',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLÉOBULE-PAULIN/CLÉOBULE-LYCANTE/CLÉOBULE-DIDYME/CLÉOBULE-DIDYME-THÉODORE/DIDYME-THÉODORE/DIDYME-PAULIN-MARCELLE-THÉODORE/VALENS-PAULIN/VALENS-STÉPHANIE/VALENS-PLACIDE-CLÉOBULE',
    ),
  ),
  'corneillep_suivante_I01' => 
  array (
    'pattern' => 
    array (
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#THEANTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#DAMON' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '1',
      'scene' => '1',
      'sceneId' => 'I01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'THÉANTE-DAMON/THÉANTE/FLORAME-THÉANTE/FLORAME-THÉANTE/FLORAME/THÉANTE-DAPHNIS/FLORAME-THÉANTE-DAPHNIS/DAPHNIS/',
    ),
  ),
  'corneillep_suivante_II01' => 
  array (
    'pattern' => 
    array (
      '#GERASTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#THEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DAMON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '2',
      'scene' => '1',
      'sceneId' => 'II01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'GÉRASTE/FLORAME/FLORAME/FLORAME-DAPHNIS/FLORAME-DAPHNIS/DAPHNIS/DAPHNIS/THÉANTE/THÉANTE-DAMON',
    ),
  ),
  'corneillep_suivante_III01' => 
  array (
    'pattern' => 
    array (
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#CLARIMOND' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'FLORAME/CLARIMOND-DAPHNIS/CLARIMOND/CLARIMOND//GÉRASTE/GÉRASTE/DAPHNIS/FLORAME-DAPHNIS',
    ),
  ),
  'corneillep_suivante_III02' => 
  array (
    'pattern' => 
    array (
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLARIMOND' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLARIMOND-DAPHNIS/CLARIMOND/CLARIMOND//GÉRASTE/GÉRASTE/DAPHNIS/FLORAME-DAPHNIS/DAPHNIS',
    ),
  ),
  'corneillep_suivante_III03' => 
  array (
    'pattern' => 
    array (
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLARIMOND' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '3',
      'scene' => '3',
      'sceneId' => 'III03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CLARIMOND/CLARIMOND//GÉRASTE/GÉRASTE/DAPHNIS/FLORAME-DAPHNIS/DAPHNIS/',
    ),
  ),
  'corneillep_suivante_IV01' => 
  array (
    'pattern' => 
    array (
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#THEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DAMON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DAPHNIS/GÉRASTE-DAPHNIS/GÉRASTE//FLORAME-DAMON/FLORAME-THÉANTE/FLORAME-DAPHNIS/FLORAME/FLORAME',
    ),
  ),
  'corneillep_suivante_V01' => 
  array (
    'pattern' => 
    array (
      '#GERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#POLEMON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#FLORAME' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#THEANTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DAMON' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DAPHNIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_suivante',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Suivante',
      'date' => 1634,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaSuivante',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'THÉANTE-DAMON/FLORAME/FLORAME//GÉRASTE-POLÉMON/GÉRASTE/GÉRASTE-DAPHNIS/GÉRASTE-FLORAME-DAPHNIS/',
    ),
  ),
  'corneillep_oedipe_V01' => 
  array (
    'pattern' => 
    array (
      '#OEDIPE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#THESEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#DIRCE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#PHORBAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#IPHICRATE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#NERINE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#PAGE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_oedipe',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'Oedipe',
      'date' => 1659,
      'lustrum' => '1656-1660',
      'genre' => 'Tragédie',
      'titleId' => 'Oedipe',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'OEDIPE-UN PAGE/OEDIPE-IPHICRATE/OEDIPE-PHORBAS-IPHICRATE/OEDIPE-IPHICRATE/OEDIPE-DIRCÉ-IPHICRATE/OEDIPE-THÉSÉE-DIRCÉ-IPHICRATE/THÉSÉE-DIRCÉ/THÉSÉE-DIRCÉ-NÉRINE/THÉSÉE-DIRCÉ-NÉRINE',
    ),
  ),
  'corneillep_nicomede_V01' => 
  array (
    'pattern' => 
    array (
      '#PRUSIAS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#FLAMINIUS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#ARSINOE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#LAODICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#NICOMEDE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#ATTALE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ARASPE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_nicomede',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'Nicomède',
      'date' => 1650,
      'lustrum' => '1646-1650',
      'genre' => 'Tragédie',
      'titleId' => 'Nicomede',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARSINOÉ-ATTALE/FLAMINIUS-ARSINOÉ-ATTALE/PRUSIAS-FLAMINIUS-ARSINOÉ-ATTALE/PRUSIAS-FLAMINIUS-ARSINOÉ-ATTALE/PRUSIAS-FLAMINIUS-ARSINOÉ-ATTALE-ARASPE/ARSINOÉ-LAODICE/ARSINOÉ-LAODICE-ATTALE/PRUSIAS-FLAMINIUS-ARSINOÉ-LAODICE-ATTALE/PRUSIAS-FLAMINIUS-ARSINOÉ-LAODICE-NICOMÈDE-ATTALE',
    ),
  ),
  'corneillep_menteur_IV01' => 
  array (
    'pattern' => 
    array (
      '#GERONTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORANTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ALCIPPE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLARICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LUCRECE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#SABINE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_menteur',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'Le Menteur',
      'date' => 1644,
      'lustrum' => '1641-1645',
      'genre' => 'Comédie',
      'titleId' => 'LeMenteur',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DORANTE/DORANTE-ALCIPPE/DORANTE/GÉRONTE-DORANTE/DORANTE/DORANTE-SABINE/SABINE/LUCRÈCE-SABINE/CLARICE-LUCRÈCE-SABINE',
    ),
  ),
  'corneillep_melite_IV01' => 
  array (
    'pattern' => 
    array (
      '#ERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#PHILANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#MELITE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CHLORIS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LISIS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLITON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_melite',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'Mélite',
      'date' => 1630,
      'lustrum' => '1626-1630',
      'genre' => 'Comédie',
      'titleId' => 'Melite',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'MÉLITE-LA NOURRICE DE MÉLITE/MÉLITE-CHLORIS/MÉLITE-CHLORIS-LISIS/MÉLITE-CHLORIS-LISIS-CLITON-LA NOURRICE DE MÉLITE/ERASTE/ERASTE-CLITON/PHILANDRE/ERASTE-PHILANDRE/ERASTE',
    ),
  ),
  'corneillep_melite_IV02' => 
  array (
    'pattern' => 
    array (
      '#ERASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#PHILANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#MELITE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CHLORIS' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LISIS' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLITON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#NOURRICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_melite',
      'act' => '4',
      'scene' => '2',
      'sceneId' => 'IV02',
      'author' => 'Corneille, Pierre',
      'title' => 'Mélite',
      'date' => 1630,
      'lustrum' => '1626-1630',
      'genre' => 'Comédie',
      'titleId' => 'Melite',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'MÉLITE-CHLORIS/MÉLITE-CHLORIS-LISIS/MÉLITE-CHLORIS-LISIS-CLITON-LA NOURRICE DE MÉLITE/ERASTE/ERASTE-CLITON/PHILANDRE/ERASTE-PHILANDRE/ERASTE/CHLORIS-LISIS',
    ),
  ),
  'corneillep_illusioncomique_II01' => 
  array (
    'pattern' => 
    array (
      '#ALCANDRE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#PRIDAMANT' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#PAGE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '2',
      'scene' => '1',
      'sceneId' => 'II01',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ALCANDRE-PRIDAMANT/MATAMORE-CLINDOR/ADRASTE-ISABELLE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR-ISABELLE-PAGE du CAPITAN/CLINDOR-ISABELLE/CLINDOR-ADRASTE/ADRASTE-LYSE/LYSE',
    ),
  ),
  'corneillep_illusioncomique_II02' => 
  array (
    'pattern' => 
    array (
      '#ALCANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#PRIDAMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLINDOR' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#PAGE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '2',
      'scene' => '2',
      'sceneId' => 'II02',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'MATAMORE-CLINDOR/ADRASTE-ISABELLE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR-ISABELLE-PAGE du CAPITAN/CLINDOR-ISABELLE/CLINDOR-ADRASTE/ADRASTE-LYSE/LYSE/ALCANDRE-PRIDAMANT',
    ),
  ),
  'corneillep_illusioncomique_III01' => 
  array (
    'pattern' => 
    array (
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#GERONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'GÉRONTE-ISABELLE/GÉRONTE/MATAMORE-CLINDOR-GÉRONTE/MATAMORE-CLINDOR/CLINDOR-LYSE/LYSE/MATAMORE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR',
    ),
  ),
  'corneillep_illusioncomique_III02' => 
  array (
    'pattern' => 
    array (
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#GERONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 1,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'GÉRONTE/MATAMORE-CLINDOR-GÉRONTE/MATAMORE-CLINDOR/CLINDOR-LYSE/LYSE/MATAMORE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR/MATAMORE-CLINDOR-ISABELLE',
    ),
  ),
  'corneillep_illusioncomique_III03' => 
  array (
    'pattern' => 
    array (
      '#MATAMORE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#CLINDOR' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#GERONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '3',
      'sceneId' => 'III03',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'MATAMORE-CLINDOR-GÉRONTE/MATAMORE-CLINDOR/CLINDOR-LYSE/LYSE/MATAMORE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR-ADRASTE-GÉRONTE-ISABELLE-LYSE',
    ),
  ),
  'corneillep_illusioncomique_III04' => 
  array (
    'pattern' => 
    array (
      '#ALCANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#PRIDAMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#CLINDOR' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#ADRASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#GERONTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '3',
      'scene' => '4',
      'sceneId' => 'III04',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'MATAMORE-CLINDOR/CLINDOR-LYSE/LYSE/MATAMORE/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR/MATAMORE-CLINDOR-ISABELLE/MATAMORE-CLINDOR-ADRASTE-GÉRONTE-ISABELLE-LYSE/ALCANDRE-PRIDAMANT',
    ),
  ),
  'corneillep_illusioncomique_IV01' => 
  array (
    'pattern' => 
    array (
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ISABELLE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LYSE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#GEOLIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ISABELLE/ISABELLE-LYSE/LYSE/MATAMORE-ISABELLE-LYSE/ISABELLE-LYSE/ISABELLE-LYSE-LE GEÔLIER/CLINDOR/CLINDOR-LE GEÔLIER/CLINDOR-ISABELLE-LYSE-LE GEÔLIER',
    ),
  ),
  'corneillep_illusioncomique_IV02' => 
  array (
    'pattern' => 
    array (
      '#ALCANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#PRIDAMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#MATAMORE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLINDOR' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#ISABELLE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#LYSE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#GEOLIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_illusioncomique',
      'act' => '4',
      'scene' => '2',
      'sceneId' => 'IV02',
      'author' => 'Corneille, Pierre',
      'title' => 'L\'Illusion comique',
      'date' => 1636,
      'lustrum' => '1636-1640',
      'genre' => 'Comédie',
      'titleId' => 'LIllusioncomique',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ISABELLE-LYSE/LYSE/MATAMORE-ISABELLE-LYSE/ISABELLE-LYSE/ISABELLE-LYSE-LE GEÔLIER/CLINDOR/CLINDOR-LE GEÔLIER/CLINDOR-ISABELLE-LYSE-LE GEÔLIER/ALCANDRE-PRIDAMANT',
    ),
  ),
  'corneillep_galeriedupalais_I01' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '1',
      'scene' => '1',
      'sceneId' => 'I01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE-ARONTE/Le Libraire du palais -La Lingère du palais/DORIMANT-Le Libraire du palais /DORIMANT-HIPPOLYTE-CLÉANTE-Le Libraire du palais -La Lingère du palais/LYSANDRE-DORIMANT-Le Libraire du palais -Le Mercier du palais/LYSANDRE-DORIMANT/LYSANDRE-DORIMANT-CLÉANTE',
    ),
  ),
  'corneillep_galeriedupalais_I02' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#ARONTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '1',
      'scene' => '2',
      'sceneId' => 'I02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'PLEIRANTE-CÉLIDÉE/CÉLIDÉE-ARONTE/Le Libraire du palais -La Lingère du palais/DORIMANT-Le Libraire du palais /DORIMANT-HIPPOLYTE-CLÉANTE-Le Libraire du palais -La Lingère du palais/LYSANDRE-DORIMANT-Le Libraire du palais -Le Mercier du palais/LYSANDRE-DORIMANT/LYSANDRE-DORIMANT-CLÉANTE/HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_I03' => 
  array (
    'pattern' => 
    array (
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '1',
      'scene' => '3',
      'sceneId' => 'I03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CÉLIDÉE-ARONTE/Le Libraire du palais -La Lingère du palais/DORIMANT-Le Libraire du palais /DORIMANT-HIPPOLYTE-CLÉANTE-Le Libraire du palais -La Lingère du palais/LYSANDRE-DORIMANT-Le Libraire du palais -Le Mercier du palais/LYSANDRE-DORIMANT/LYSANDRE-DORIMANT-CLÉANTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_II01' => 
  array (
    'pattern' => 
    array (
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DORIMANT' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '2',
      'scene' => '1',
      'sceneId' => 'II01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DORIMANT-HIPPOLYTE/LYSANDRE-DORIMANT-HIPPOLYTE/LYSANDRE-DORIMANT/DORIMANT/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/CÉLIDÉE/LYSANDRE-CÉLIDÉE/LYSANDRE',
    ),
  ),
  'corneillep_galeriedupalais_III01' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '1',
      'sceneId' => 'III01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'LYSANDRE-ARONTE/ARONTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/LYSANDRE-CÉLIDÉE-HIPPOLYTE/LYSANDRE-HIPPOLYTE/PLEIRANTE-CHRYSANTE/CHRYSANTE-HIPPOLYTE/HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_III02' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '2',
      'sceneId' => 'III02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'ARONTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/LYSANDRE-CÉLIDÉE-HIPPOLYTE/LYSANDRE-HIPPOLYTE/PLEIRANTE-CHRYSANTE/CHRYSANTE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_III03' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '3',
      'sceneId' => 'III03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/LYSANDRE-CÉLIDÉE-HIPPOLYTE/LYSANDRE-HIPPOLYTE/PLEIRANTE-CHRYSANTE/CHRYSANTE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE/DORIMANT-CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_III04' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#CHRYSANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '3',
      'scene' => '4',
      'sceneId' => 'III04',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CÉLIDÉE-HIPPOLYTE/LYSANDRE-CÉLIDÉE-HIPPOLYTE/LYSANDRE-HIPPOLYTE/PLEIRANTE-CHRYSANTE/CHRYSANTE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE/DORIMANT-CÉLIDÉE/DORIMANT',
    ),
  ),
  'corneillep_galeriedupalais_IV01' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '1',
      'sceneId' => 'IV01',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'HIPPOLYTE-ARONTE/DORIMANT-CÉLIDÉE-ARONTE/DORIMANT-CÉLIDÉE/LYSANDRE-ARONTE/LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE',
    ),
  ),
  'corneillep_galeriedupalais_IV02' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '2',
      'sceneId' => 'IV02',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DORIMANT-CÉLIDÉE-ARONTE/DORIMANT-CÉLIDÉE/LYSANDRE-ARONTE/LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_IV03' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#DORIMANT' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '3',
      'sceneId' => 'IV03',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'DORIMANT-CÉLIDÉE/LYSANDRE-ARONTE/LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE',
    ),
  ),
  'corneillep_galeriedupalais_IV04' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '4',
      'sceneId' => 'IV04',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'LYSANDRE-ARONTE/LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE/Le Mercier du palais-La Lingère du palais',
    ),
  ),
  'corneillep_galeriedupalais_IV05' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '5',
      'sceneId' => 'IV05',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'LYSANDRE/LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE/Le Mercier du palais-La Lingère du palais/CLÉANTE-Le Libraire du palais -Le Mercier du palais-La Lingère du palais',
    ),
  ),
  'corneillep_galeriedupalais_IV06' => 
  array (
    'pattern' => 
    array (
      '#PLEIRANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 1,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#LYSANDRE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#CELIDEE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#HIPPOLYTE' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 0,
      ),
      '#ARONTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLEANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#LIBRAIRE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 0,
      ),
      '#MERCIER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#LINGERE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_galeriedupalais',
      'act' => '4',
      'scene' => '6',
      'sceneId' => 'IV06',
      'author' => 'Corneille, Pierre',
      'title' => 'La Galerie du palais',
      'date' => 1633,
      'lustrum' => '1631-1635',
      'genre' => 'Comédie',
      'titleId' => 'LaGaleriedupalais',
      'genreId' => 'Comedie',
      'authorId' => 'CorneillePierre',
      'string' => 'LYSANDRE-HIPPOLYTE/HIPPOLYTE/CÉLIDÉE-HIPPOLYTE/PLEIRANTE-HIPPOLYTE/PLEIRANTE-CÉLIDÉE/CÉLIDÉE/Le Mercier du palais-La Lingère du palais/CLÉANTE-Le Libraire du palais -Le Mercier du palais-La Lingère du palais/ARONTE-Le Mercier du palais-La Lingère du palais',
    ),
  ),
  'corneillep_clitandre_I01' => 
  array (
    'pattern' => 
    array (
      '#ROSIDOR' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#PYMANTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CALISTE' => 
      array (
        0 => 1,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#DORISE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#LYSARQUE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#GERONTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#CLEON' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 1,
        7 => 0,
        8 => 0,
      ),
      '#LYCASTE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_clitandre',
      'act' => '1',
      'scene' => '1',
      'sceneId' => 'I01',
      'author' => 'Corneille, Pierre',
      'title' => 'Clitandre',
      'date' => 1631,
      'lustrum' => '1631-1635',
      'genre' => 'Tragédie',
      'titleId' => 'Clitandre',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'CALISTE/ROSIDOR-LYSARQUE/CALISTE/CALISTE-DORISE/PYMANTE-GÉRONTE/PYMANTE-GÉRONTE-LYCASTE/LYSARQUE-CLÉON/CALISTE-DORISE/ROSIDOR-PYMANTE-CALISTE-DORISE-GÉRONTE-LYCASTE',
    ),
  ),
  'corneillep_agesilas_V01' => 
  array (
    'pattern' => 
    array (
      '#AGESILAS' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#LYSANDER' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 1,
        6 => 1,
        7 => 1,
        8 => 1,
      ),
      '#COTYS' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#SPITRIDATE' => 
      array (
        0 => 0,
        1 => 1,
        2 => 1,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#MANDANE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 1,
        3 => 1,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#ELPINICE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 0,
        8 => 1,
      ),
      '#AGLATIDE' => 
      array (
        0 => 0,
        1 => 0,
        2 => 0,
        3 => 0,
        4 => 0,
        5 => 0,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
      '#XENOCLES' => 
      array (
        0 => 1,
        1 => 1,
        2 => 1,
        3 => 1,
        4 => 1,
        5 => 1,
        6 => 0,
        7 => 1,
        8 => 1,
      ),
    ),
    'id' => 
    array (
      'play' => 'corneillep_agesilas',
      'act' => '5',
      'scene' => '1',
      'sceneId' => 'V01',
      'author' => 'Corneille, Pierre',
      'title' => 'Agésilas',
      'date' => 1666,
      'lustrum' => '1666-1670',
      'genre' => 'Tragédie',
      'titleId' => 'Agesilas',
      'genreId' => 'Tragedie',
      'authorId' => 'CorneillePierre',
      'string' => 'AGÉSILAS-XENOCLES/AGÉSILAS-SPITRIDATE-XENOCLES/AGÉSILAS-SPITRIDATE-MANDANE-XENOCLES/AGÉSILAS-MANDANE-XENOCLES/AGÉSILAS-XENOCLES/AGÉSILAS-LYSANDER-XENOCLES/AGÉSILAS-LYSANDER/AGÉSILAS-LYSANDER-AGLATIDE-XENOCLES/AGÉSILAS-LYSANDER-COTYS-SPITRIDATE-MANDANE-ELPINICE-AGLATIDE-XENOCLES',
    ),
  ),
); ?>